version: 2
updates:
  - package-ecosystem: pip
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:17"
      timezone: Etc/UTC
    open-pull-requests-limit: 5
    labels: [dependencies]
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
      day: monday
      time: "06:29"
      timezone: Etc/UTC
    open-pull-requests-limit: 3
    labels: [dependencies]

